version: "3"
services:
  #PHP Service
  app:
    image: onlineclinique.azurecr.io/onlinecliniqueimage:latest
    container_name: laravel_api
    restart: unless-stopped
    tty: true
    env_file: .env
    working_dir: /var/www
    ports:
      - "9000:9000"
      # - "443:443"
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 2468147aZ!!
      MYSQL_PASSWORD: 2468147aZ!!
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: root
      MYSQL_ROOT_PASSWORD: 2468147aZ!!

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
